package oop.homeWork5_6.film;

public enum Genre {

    ACTION, WESTERNS, DRAMAS, DETECTIVES, BIOGRAPHY, MELODRAMAS,
    COMEDY, CRIMINAL, THRYLLERS, HISTORICAL, DOCUMENTARY, ADVANTURE,
    MYSTICAL, HORRORS, FAMILY, SPORTS, FANTASTIC, MUSICALS

}

